version: '3.1'
services:
  greenmail:
    image: greenmail/standalone
    ports:
      - 3143:3143
      - 3993:3993
      - 8080:8080
    environment:
      GREENMAIL_OPTS: '
        -Dgreenmail.imap
        -Dgreenmail.imaps
        -Dgreenmail.hostname=0.0.0.0 
        -Dgreenmail.users=user:pass@localhost
        -Dgreenmail.verbose
        '